spring.application.name=gateway-service-api
server.port=9090

eureka.client.service-url.defaultZone = http://localhost:8761/eureka


#================keycloak configurations
spring.security.oauth2.resourceserver.jwt.token-uri=http://localhost:8080/realms/ec7205 /protocol/openid-connect/token
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/ec7205
public.key.string=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApU/j0Bfrcoift2/z2C1ba0eC4HpcHOMcL/WNAlVXtObQ7L1g7110ZM//qCfIHrdAJ38Y+AC9oerM/aLXHrMZVzDaV5gvGIcaTnFdS1fonpzkp+4woN7pShBapkxr7P6WnYvrGWhuEaSfOHJ/tXld7NbKks+6k11Z9GW6KU4Zh0+sahW9X8alaHBDkZJRSNq7COlWyDeWSwJFb7CHXsTod/EQ7+qXAZagplPve+Pw6OOv8RTGqNDNlXVTwrT245ih/IqybxekCxXNw0wYiPrjcPa/4nmssaKlrfm11l0V/uQyW9SHlk1zhaQbVtrWjGT9kTD0G580oNEmbMlyc2dlMwIDAQAB

keycloak.config.realm=ec7205
keycloak.config.server-url=http://localhost:8080/
keycloak.config.client-id=ec7205-client
keycloak.config.grant-type=password
keycloak.config.name=amirumithsara1234@gmail.com
keycloak.config.secret=yJq1nWO8BsEteqCXcDu3CEVZ2quiXus9
keycloak.config.password=1234
